/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/advisor/analyse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AnalyseRequest'];
          'text/json': components['schemas']['AnalyseRequest'];
          'application/*+json': components['schemas']['AnalyseRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['AdvisorResult'];
            'application/json': components['schemas']['AdvisorResult'];
            'text/json': components['schemas']['AdvisorResult'];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ErrorResult'];
            'application/json': components['schemas']['ErrorResult'];
            'text/json': components['schemas']['ErrorResult'];
          };
        };
        /** @description Service Unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ErrorResult'];
            'application/json': components['schemas']['ErrorResult'];
            'text/json': components['schemas']['ErrorResult'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Asset'][];
            'application/json': components['schemas']['Asset'][];
            'text/json': components['schemas']['Asset'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateAssetRequest'];
          'text/json': components['schemas']['CreateAssetRequest'];
          'application/*+json': components['schemas']['CreateAssetRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Asset'];
            'application/json': components['schemas']['Asset'];
            'text/json': components['schemas']['Asset'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['AssetSummary'][];
            'application/json': components['schemas']['AssetSummary'][];
            'text/json': components['schemas']['AssetSummary'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/allocation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['AssetAllocation'][];
            'application/json': components['schemas']['AssetAllocation'][];
            'text/json': components['schemas']['AssetAllocation'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/gain-loss': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['PortfolioGainLoss'];
            'application/json': components['schemas']['PortfolioGainLoss'];
            'text/json': components['schemas']['PortfolioGainLoss'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/performance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['MonthlyPerformance'][];
            'application/json': components['schemas']['MonthlyPerformance'][];
            'text/json': components['schemas']['MonthlyPerformance'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string[];
            'application/json': string[];
            'text/json': string[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Asset'];
            'application/json': components['schemas']['Asset'];
            'text/json': components['schemas']['Asset'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateAssetRequest'];
          'text/json': components['schemas']['UpdateAssetRequest'];
          'application/*+json': components['schemas']['UpdateAssetRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/assets/{id}/prices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddPriceRequest'];
          'text/json': components['schemas']['AddPriceRequest'];
          'application/*+json': components['schemas']['AddPriceRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProfileResponse'];
            'application/json': components['schemas']['ProfileResponse'];
            'text/json': components['schemas']['ProfileResponse'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProfileRequest'];
          'text/json': components['schemas']['UpdateProfileRequest'];
          'application/*+json': components['schemas']['UpdateProfileRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/budgets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          year?: number;
          month?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Budget'][];
            'application/json': components['schemas']['Budget'][];
            'text/json': components['schemas']['Budget'][];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpsertBudgetRequest'];
          'text/json': components['schemas']['UpsertBudgetRequest'];
          'application/*+json': components['schemas']['UpsertBudgetRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/budgets/usage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          year?: number;
          month?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BudgetUsageResponse'][];
            'application/json': components['schemas']['BudgetUsageResponse'][];
            'text/json': components['schemas']['BudgetUsageResponse'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{goalId}/contributions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          goalId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['GoalContribution'][];
            'application/json': components['schemas']['GoalContribution'][];
            'text/json': components['schemas']['GoalContribution'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          goalId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddContributionRequest'];
          'text/json': components['schemas']['AddContributionRequest'];
          'application/*+json': components['schemas']['AddContributionRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['GoalContribution'];
            'application/json': components['schemas']['GoalContribution'];
            'text/json': components['schemas']['GoalContribution'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{goalId}/contributions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          goalId: string;
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['DashboardSummary'];
            'application/json': components['schemas']['DashboardSummary'];
            'text/json': components['schemas']['DashboardSummary'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dashboard/spending-trend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          months?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['SpendingTrendPoint'][];
            'application/json': components['schemas']['SpendingTrendPoint'][];
            'text/json': components['schemas']['SpendingTrendPoint'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['GoalProgressDto'][];
            'application/json': components['schemas']['GoalProgressDto'][];
            'text/json': components['schemas']['GoalProgressDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateGoalRequest'];
          'text/json': components['schemas']['CreateGoalRequest'];
          'application/*+json': components['schemas']['CreateGoalRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['SavingsGoal'];
            'application/json': components['schemas']['SavingsGoal'];
            'text/json': components['schemas']['SavingsGoal'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['GoalProgressDto'];
            'application/json': components['schemas']['GoalProgressDto'];
            'text/json': components['schemas']['GoalProgressDto'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateGoalRequest'];
          'text/json': components['schemas']['UpdateGoalRequest'];
          'application/*+json': components['schemas']['UpdateGoalRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateStatusRequest'];
          'text/json': components['schemas']['UpdateStatusRequest'];
          'application/*+json': components['schemas']['UpdateStatusRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{id}/abandon': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AbandonGoalRequest'];
          'text/json': components['schemas']['AbandonGoalRequest'];
          'application/*+json': components['schemas']['AbandonGoalRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/goals/{id}/projection': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProjectionResult'];
            'application/json': components['schemas']['ProjectionResult'];
            'text/json': components['schemas']['ProjectionResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/liabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Liability'][];
            'application/json': components['schemas']['Liability'][];
            'text/json': components['schemas']['Liability'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateLiabilityRequest'];
          'text/json': components['schemas']['CreateLiabilityRequest'];
          'application/*+json': components['schemas']['CreateLiabilityRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Liability'];
            'application/json': components['schemas']['Liability'];
            'text/json': components['schemas']['Liability'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/liabilities/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Liability'];
            'application/json': components['schemas']['Liability'];
            'text/json': components['schemas']['Liability'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateLiabilityRequest'];
          'text/json': components['schemas']['UpdateLiabilityRequest'];
          'application/*+json': components['schemas']['UpdateLiabilityRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/liabilities/{id}/amounts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddAmountRequest'];
          'text/json': components['schemas']['AddAmountRequest'];
          'application/*+json': components['schemas']['AddAmountRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/liabilities/types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string[];
            'application/json': string[];
            'text/json': string[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/networth': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['NetWorthSnapshot'];
            'application/json': components['schemas']['NetWorthSnapshot'];
            'text/json': components['schemas']['NetWorthSnapshot'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/networth/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['NetWorthHistoryPoint'][];
            'application/json': components['schemas']['NetWorthHistoryPoint'][];
            'text/json': components['schemas']['NetWorthHistoryPoint'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/reports/monthly': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          year?: number;
          month?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['MonthlyReport'];
            'application/json': components['schemas']['MonthlyReport'];
            'text/json': components['schemas']['MonthlyReport'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProblemDetails'];
            'application/json': components['schemas']['ProblemDetails'];
            'text/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/dev/seed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          category?: string;
          minAmount?: number;
          maxAmount?: number;
          keyword?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Transaction'][];
            'application/json': components['schemas']['Transaction'][];
            'text/json': components['schemas']['Transaction'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['TransactionRequest'];
          'text/json': components['schemas']['TransactionRequest'];
          'application/*+json': components['schemas']['TransactionRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['Transaction'];
            'application/json': components['schemas']['Transaction'];
            'text/json': components['schemas']['Transaction'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['TransactionRequest'];
          'text/json': components['schemas']['TransactionRequest'];
          'application/*+json': components['schemas']['TransactionRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/transactions/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['TransactionCategoriesResponse'];
            'application/json': components['schemas']['TransactionCategoriesResponse'];
            'text/json': components['schemas']['TransactionCategoriesResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AbandonGoalRequest: {
      /** Format: date-time */
      date?: string;
      reason?: string | null;
      description?: string | null;
    };
    AddAmountRequest: {
      /** Format: double */
      value?: number;
      /** Format: date-time */
      date?: string;
    };
    AddContributionRequest: {
      /** Format: double */
      amount?: number;
      /** Format: date-time */
      date?: string;
      reason?: string | null;
      description?: string | null;
      note?: string | null;
    };
    AddPriceRequest: {
      /** Format: double */
      value?: number;
      /** Format: date-time */
      date?: string;
    };
    AdvisorResult: {
      provider?: string | null;
      tips?: string | null;
    };
    AmountEntry: {
      /** Format: double */
      value?: number;
      /** Format: date-time */
      date?: string;
    };
    AnalyseRequest: {
      provider?: string | null;
      goals?: string[] | null;
      apiKey?: string | null;
    };
    Asset: {
      id?: string | null;
      userId?: string | null;
      name?: string | null;
      type?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: double */
      purchasePrice?: number;
      /** Format: date-time */
      purchaseDate?: string;
      price?: components['schemas']['PriceEntry'][] | null;
    };
    AssetAllocation: {
      type?: string | null;
      /** Format: double */
      totalValue?: number;
      /** Format: double */
      allocationPercent?: number;
    };
    AssetSummary: {
      id?: string | null;
      name?: string | null;
      type?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: double */
      purchasePrice?: number;
      /** Format: double */
      currentPrice?: number;
      /** Format: double */
      currentValue?: number;
      /** Format: double */
      unrealisedGainLoss?: number;
      /** Format: double */
      unrealisedGainLossPercent?: number;
    };
    Budget: {
      id?: string | null;
      userId?: string | null;
      category?: string | null;
      /** Format: date-time */
      date?: string;
      /** Format: double */
      limitAmount?: number;
    };
    BudgetUsage: {
      category?: string | null;
      /** Format: double */
      limit?: number;
      /** Format: double */
      spent?: number;
      /** Format: double */
      readonly remaining?: number;
      /** Format: double */
      readonly usagePercent?: number;
    };
    BudgetUsageResponse: {
      category?: string | null;
      /** Format: double */
      limit?: number;
      /** Format: double */
      spent?: number;
      /** Format: double */
      remaining?: number;
      /** Format: double */
      usagePercent?: number;
    };
    CreateAssetRequest: {
      name?: string | null;
      type?: string | null;
      /** Format: double */
      quantity?: number;
      /** Format: double */
      purchasePrice?: number;
      /** Format: date-time */
      purchaseDate?: string;
    };
    CreateGoalRequest: {
      name?: string | null;
      /** Format: double */
      targetAmount?: number;
      /** Format: date-time */
      deadline?: string;
      description?: string | null;
    };
    CreateLiabilityRequest: {
      name?: string | null;
      type?: string | null;
      /** Format: double */
      initialAmount?: number;
      /** Format: date-time */
      date?: string;
    };
    DashboardSummary: {
      /** Format: double */
      netWorth?: number;
      /** Format: double */
      totalInvested?: number;
      /** Format: double */
      totalSaved?: number;
      /** Format: double */
      monthlyIncome?: number;
      /** Format: double */
      monthlyExpenses?: number;
      budgetUsage?: components['schemas']['BudgetUsage'][] | null;
      activeGoals?: components['schemas']['GoalProgress'][] | null;
    };
    ErrorResult: {
      error?: string | null;
    };
    GoalContribution: {
      id?: string | null;
      goalId?: string | null;
      userId?: string | null;
      /** Format: double */
      amount?: number;
      /** Format: date-time */
      date?: string;
      reason?: string | null;
      description?: string | null;
      /** Format: double */
      balanceAfter?: number;
    };
    GoalContributionSummary: {
      goalId?: string | null;
      goalName?: string | null;
      /** Format: double */
      totalDeposited?: number;
      /** Format: double */
      totalWithdrawn?: number;
      /** Format: double */
      readonly netContribution?: number;
      /** Format: int32 */
      contributionCount?: number;
    };
    GoalProgress: {
      goalId?: string | null;
      name?: string | null;
      /** Format: double */
      currentAmount?: number;
      /** Format: double */
      targetAmount?: number;
      /** Format: double */
      readonly percentReached?: number;
      /** Format: date-time */
      projectedCompletion?: string | null;
    };
    GoalProgressDto: {
      id?: string | null;
      userId?: string | null;
      name?: string | null;
      /** Format: double */
      targetAmount?: number;
      /** Format: double */
      currentBalance?: number;
      /** Format: double */
      readonly percentReached?: number;
      /** Format: double */
      readonly amountRemaining?: number;
      /** Format: date-time */
      projectedCompletion?: string | null;
      status?: components['schemas']['GoalStatus'];
      /** Format: date-time */
      deadline?: string;
      description?: string | null;
    };
    /**
     * Format: int32
     * @enum {integer}
     */
    GoalStatus: 0 | 1 | 2 | 3;
    Liability: {
      id?: string | null;
      userId?: string | null;
      name?: string | null;
      type?: string | null;
      amount?: components['schemas']['AmountEntry'][] | null;
    };
    MonthlyPerformance: {
      month?: string | null;
      /** Format: double */
      startValue?: number;
      /** Format: double */
      endValue?: number;
      /** Format: double */
      gainLoss?: number;
      /** Format: double */
      gainLossPercent?: number;
    };
    MonthlyReport: {
      /** Format: int32 */
      year?: number;
      /** Format: int32 */
      month?: number;
      /** Format: double */
      totalIncome?: number;
      /** Format: double */
      totalExpenses?: number;
      /** Format: double */
      readonly netSavings?: number;
      expensesByCategory?: {
        [key: string]: number;
      } | null;
      incomeByCategory?: {
        [key: string]: number;
      } | null;
      savingsContributions?: components['schemas']['GoalContributionSummary'][] | null;
      portfolioChange?: components['schemas']['PortfolioChangeSummary'];
    };
    NetWorthHistoryPoint: {
      /** Format: date-time */
      date?: string;
      /** Format: double */
      totalAssets?: number;
      /** Format: double */
      totalLiabilities?: number;
      /** Format: double */
      netWorth?: number;
    };
    NetWorthSnapshot: {
      /** Format: double */
      totalAssets?: number;
      /** Format: double */
      totalLiabilities?: number;
      /** Format: double */
      netWorth?: number;
    };
    PortfolioChangeSummary: {
      /** Format: double */
      startValue?: number;
      /** Format: double */
      endValue?: number;
      /** Format: double */
      readonly change?: number;
      /** Format: double */
      readonly changePercent?: number;
    };
    PortfolioGainLoss: {
      /** Format: double */
      totalInvested?: number;
      /** Format: double */
      currentValue?: number;
      /** Format: double */
      totalGainLoss?: number;
      /** Format: double */
      totalGainLossPercent?: number;
    };
    PriceEntry: {
      /** Format: double */
      value?: number;
      /** Format: date-time */
      date?: string;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & {
      [key: string]: unknown;
    };
    ProfileResponse: {
      uid?: string | null;
      displayName?: string | null;
      email?: string | null;
      currency?: string | null;
    };
    ProjectionResult: {
      /** Format: date-time */
      projectedCompletion?: string | null;
      reason?: string | null;
    };
    SavingsGoal: {
      id?: string | null;
      userId?: string | null;
      name?: string | null;
      /** Format: double */
      targetAmount?: number;
      /** Format: double */
      currentAmount?: number;
      /** Format: date-time */
      deadline?: string;
      description?: string | null;
      status?: components['schemas']['GoalStatus'];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    SpendingTrendPoint: {
      month?: string | null;
      expenses?: {
        [key: string]: number;
      } | null;
    };
    Transaction: {
      id?: string | null;
      userId?: string | null;
      /** Format: double */
      amount?: number;
      /** Format: date-time */
      date?: string;
      category?: string | null;
      description?: string | null;
    };
    TransactionCategoriesResponse: {
      expense?: string[] | null;
      income?: string[] | null;
    };
    TransactionRequest: {
      /** Format: double */
      amount?: number;
      /** Format: date-time */
      date?: string;
      category?: string | null;
      description?: string | null;
    };
    UpdateAssetRequest: {
      name?: string | null;
      type?: string | null;
      /** Format: double */
      quantity?: number;
    };
    UpdateGoalRequest: {
      name?: string | null;
      /** Format: double */
      targetAmount?: number;
      /** Format: date-time */
      deadline?: string;
      description?: string | null;
    };
    UpdateLiabilityRequest: {
      name?: string | null;
      type?: string | null;
    };
    UpdateProfileRequest: {
      displayName?: string | null;
      email?: string | null;
      currency?: string | null;
    };
    UpdateStatusRequest: {
      status?: components['schemas']['GoalStatus'];
    };
    UpsertBudgetRequest: {
      /** Format: int32 */
      year?: number;
      /** Format: int32 */
      month?: number;
      category?: string | null;
      /** Format: double */
      limitAmount?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
