spring.application.name=budget-app

spring.datasource.url=jdbc:postgresql://localhost:5432/budget_app
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.security.user.email=user@budget.app
app.security.user.password=password

app.jwt.secret=YnVkZ2V0LWFwcC1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
app.jwt.expiration=86400000
